# Generated by Django 4.2.6 on 2023-11-25 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('relized_by', models.CharField(max_length=300)),
                ('link_creator', models.SlugField()),
                ('relized_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='GameDl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('link_creator', models.SlugField()),
                ('relized_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('recommendation', models.BooleanField(default=True)),
                ('relized_by', models.CharField(max_length=300)),
                ('relized_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='SubCtegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('discription', models.TextField()),
                ('category', models.ManyToManyField(to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('relized_by', models.CharField(max_length=300)),
                ('relized_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.review')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID продукта')),
                ('operating_system', models.CharField(choices=[('L', 'Linux'), ('W', 'Windows'), ('M', 'MacOS'), ('P', 'PlayStation'), ('X', 'XBox')], help_text='Укажите ОС', max_length=2, verbose_name='ОС')),
                ('device_processor', models.CharField(help_text='Укажите процессор', max_length=100, verbose_name='Процессор')),
                ('device_memory', models.CharField(help_text='Укажите колличество ОЗУ', max_length=100, verbose_name='Колличество ОЗУ')),
                ('device_storage', models.CharField(help_text='Укажите колличество памяти на Диске', max_length=100, verbose_name='Колличество памяти на Диске')),
                ('device_graphics', models.CharField(help_text='Укажиет модель видеокарты и колличество памяти', max_length=100, verbose_name='Модель видеокарты и колличество памяти')),
                ('type_requirements', models.CharField(choices=[('M', 'Minimals'), ('R', 'Recommends')], help_text='Укажите тип системных требований', max_length=2, verbose_name='Тип системных требований')),
                ('game', models.ForeignKey(limit_choices_to={'type': 'G'}, on_delete=django.db.models.deletion.CASCADE, related_name='system_requirements', to='core.game')),
            ],
            options={
                'verbose_name': 'системная характеристика',
                'verbose_name_plural': 'системные характеристики',
                'db_table': 'system_requirement',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='game',
            name='subcategory',
            field=models.ManyToManyField(to='core.subctegory'),
        ),
    ]
