# Generated by Django 4.2.6 on 2023-11-25 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_game_gamedl_review_subctegory_subreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('discription', models.TextField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='systemrequirement',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AlterField(
            model_name='gamedl',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SubCtegory',
        ),
        migrations.DeleteModel(
            name='SystemRequirement',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
